#Stage 1 Build
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
     - "80:3000" #maps ec2 80 to docker 3000.
    environment:
     - NODE_ENV=production
    restart: unless-stopped